import { ROUTES } from '@/constants'
import { APP_ROLES, type AppRole } from '@/types/auth'

export const APP_PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  MAESTROS_MANAGE: 'maestros.manage',
  CONFIG_PRECIOS_MANAGE: 'config_precios.manage',
  CONFIG_PARAMETROS_MANAGE: 'config_parametros.manage',
  LIQUIDACIONES_AGRI_VIEW: 'liquidaciones_agri.view',
  LIQUIDACIONES_AGRI_PAY: 'liquidaciones_agri.pay',
  PLANILLAS_VIEW: 'planillas.view',
  PLANILLAS_PAY: 'planillas.pay',
  AGRICULTORES_VIEW: 'agricultores.view',
  AGRICULTORES_MANAGE: 'agricultores.manage',
  LOTES_VIEW: 'lotes.view',
  LOTES_CREATE: 'lotes.create',
  LOTES_DELETE: 'lotes.delete',
  LOTES_PRINT_TICKET: 'lotes.print_ticket',
  LOTES_PRINT_LABELS: 'lotes.print_labels',
  LOTES_PROCESS: 'lotes.process',
  LOTES_DISPATCH: 'lotes.dispatch',
  DESPACHOS_VIEW: 'despachos.view',
  DESPACHOS_MANAGE: 'despachos.manage',
  AUDIT_VIEW: 'audit.view',
} as const

export type AppPermission = (typeof APP_PERMISSIONS)[keyof typeof APP_PERMISSIONS]

const ALL_PERMISSIONS = Object.values(APP_PERMISSIONS)

const ROLE_PERMISSIONS: Record<string, AppPermission[]> = {
  [APP_ROLES.ADMIN]: ALL_PERMISSIONS,
  [APP_ROLES.GERENCIA]: ALL_PERMISSIONS,
  [APP_ROLES.ADMINISTRADOR_PLANTA]: [
    APP_PERMISSIONS.DASHBOARD_VIEW,
    APP_PERMISSIONS.LIQUIDACIONES_AGRI_VIEW,
    APP_PERMISSIONS.PLANILLAS_VIEW,
    APP_PERMISSIONS.AGRICULTORES_VIEW,
    APP_PERMISSIONS.CONFIG_PRECIOS_MANAGE,
    APP_PERMISSIONS.LOTES_VIEW,
    APP_PERMISSIONS.LOTES_CREATE,
    APP_PERMISSIONS.LOTES_DELETE,
    APP_PERMISSIONS.LOTES_PRINT_TICKET,
    APP_PERMISSIONS.LOTES_PRINT_LABELS,
    APP_PERMISSIONS.LOTES_PROCESS,
    APP_PERMISSIONS.LOTES_DISPATCH,
    APP_PERMISSIONS.DESPACHOS_VIEW,
    APP_PERMISSIONS.DESPACHOS_MANAGE,
  ],
  [APP_ROLES.TESORERIA]: [
    APP_PERMISSIONS.LIQUIDACIONES_AGRI_VIEW,
    APP_PERMISSIONS.LIQUIDACIONES_AGRI_PAY,
    APP_PERMISSIONS.PLANILLAS_VIEW,
    APP_PERMISSIONS.PLANILLAS_PAY,
  ],
  [APP_ROLES.OPERATIVO_RECEPCION]: [
    APP_PERMISSIONS.AGRICULTORES_VIEW,
    APP_PERMISSIONS.LOTES_VIEW,
    APP_PERMISSIONS.LOTES_CREATE,
    APP_PERMISSIONS.LOTES_PRINT_TICKET,
  ],
  [APP_ROLES.OPERATIVO_PLANTA]: [
    APP_PERMISSIONS.LOTES_VIEW,
    APP_PERMISSIONS.LOTES_CREATE,
    APP_PERMISSIONS.LOTES_PRINT_TICKET,
    APP_PERMISSIONS.LOTES_PRINT_LABELS,
    APP_PERMISSIONS.LOTES_PROCESS,
  ],
  [APP_ROLES.OPERATIVO_PLANTA_DESPACHO]: [
    APP_PERMISSIONS.LOTES_VIEW,
    APP_PERMISSIONS.LOTES_CREATE,
    APP_PERMISSIONS.LOTES_DELETE,
    APP_PERMISSIONS.LOTES_PRINT_TICKET,
    APP_PERMISSIONS.LOTES_PRINT_LABELS,
    APP_PERMISSIONS.LOTES_PROCESS,
    APP_PERMISSIONS.LOTES_DISPATCH,
    APP_PERMISSIONS.DESPACHOS_VIEW,
    APP_PERMISSIONS.DESPACHOS_MANAGE,
  ],
}

const ROUTE_PERMISSIONS: Record<string, AppPermission> = {
  [ROUTES.DASHBOARD]: APP_PERMISSIONS.DASHBOARD_VIEW,
  [ROUTES.AGRICULTORES]: APP_PERMISSIONS.AGRICULTORES_VIEW,
  [ROUTES.ACOPIADORES]: APP_PERMISSIONS.MAESTROS_MANAGE,
  [ROUTES.COLABORADORES]: APP_PERMISSIONS.MAESTROS_MANAGE,
  [ROUTES.PRODUCTOS]: APP_PERMISSIONS.MAESTROS_MANAGE,
  [ROUTES.CENTROS_ACOPIO]: APP_PERMISSIONS.MAESTROS_MANAGE,
  [ROUTES.LOTES]: APP_PERMISSIONS.LOTES_VIEW,
  [ROUTES.LOTES_DETALLE]: APP_PERMISSIONS.LOTES_VIEW,
  [ROUTES.CLASIFICACIONES]: APP_PERMISSIONS.LOTES_PROCESS,
  [ROUTES.EMPAQUETAR]: APP_PERMISSIONS.LOTES_PROCESS,
  [ROUTES.DESPACHOS]: APP_PERMISSIONS.DESPACHOS_VIEW,
  [ROUTES.DESPACHOS_NUEVO]: APP_PERMISSIONS.LOTES_DISPATCH,
  [ROUTES.DESPACHOS_DETALLE]: APP_PERMISSIONS.DESPACHOS_VIEW,
  [ROUTES.DESPACHOS_EDITAR]: APP_PERMISSIONS.DESPACHOS_MANAGE,
  [ROUTES.CUBETAS]: APP_PERMISSIONS.DASHBOARD_VIEW,
  [ROUTES.LIQUIDACIONES_AGRI]: APP_PERMISSIONS.LIQUIDACIONES_AGRI_VIEW,
  [ROUTES.LIQUIDACIONES_AGRI_NUEVA]: APP_PERMISSIONS.LIQUIDACIONES_AGRI_VIEW,
  [ROUTES.LIQUIDACIONES_AGRI_DETALLE]: APP_PERMISSIONS.LIQUIDACIONES_AGRI_VIEW,
  [ROUTES.PLANILLAS]: APP_PERMISSIONS.PLANILLAS_VIEW,
  [ROUTES.TAREO]: APP_PERMISSIONS.DASHBOARD_VIEW,
  [ROUTES.CONFIG_PRECIOS]: APP_PERMISSIONS.CONFIG_PRECIOS_MANAGE,
  [ROUTES.CONFIG_PARAMETROS]: APP_PERMISSIONS.CONFIG_PARAMETROS_MANAGE,
  [ROUTES.AUDIT_LOG]: APP_PERMISSIONS.AUDIT_VIEW,
}

export function hasPermission(roles: AppRole[], permission: AppPermission): boolean {
  if (roles.includes(APP_ROLES.ADMIN) || roles.includes(APP_ROLES.GERENCIA)) {
    return true
  }

  if (roles.length === 0) {
    const fallbackPermisos: AppPermission[] = [
      APP_PERMISSIONS.DASHBOARD_VIEW,
      APP_PERMISSIONS.LIQUIDACIONES_AGRI_VIEW,
      APP_PERMISSIONS.PLANILLAS_VIEW,
      APP_PERMISSIONS.AGRICULTORES_VIEW,
      APP_PERMISSIONS.LOTES_VIEW,
      APP_PERMISSIONS.LOTES_CREATE,
      APP_PERMISSIONS.LOTES_DELETE,
      APP_PERMISSIONS.LOTES_PRINT_TICKET,
      APP_PERMISSIONS.LOTES_PRINT_LABELS,
      APP_PERMISSIONS.LOTES_PROCESS,
      APP_PERMISSIONS.LOTES_DISPATCH,
      APP_PERMISSIONS.DESPACHOS_VIEW,
      APP_PERMISSIONS.DESPACHOS_MANAGE,
    ]

    return fallbackPermisos.includes(permission)
  }

  return roles.some((role) => ROLE_PERMISSIONS[role]?.includes(permission))
}

export function canAccessRoute(roles: AppRole[], route: string): boolean {
  const permission = ROUTE_PERMISSIONS[route]

  if (!permission) {
    return roles.length === 0 || roles.includes(APP_ROLES.ADMIN)
  }

  return hasPermission(roles, permission)
}

export function getDefaultRouteForRoles(roles: AppRole[]): string {
  const candidates = [
    ROUTES.DASHBOARD,
    ROUTES.PLANILLAS,
    ROUTES.LIQUIDACIONES_AGRI,
    ROUTES.LOTES,
    ROUTES.AGRICULTORES,
  ]

  return candidates.find((route) => canAccessRoute(roles, route)) ?? ROUTES.LOGIN
}